import { z } from 'zod';

export const ClientDto = z.object({
    name: z.string(),
    changes: z.any().optional(),
    updatedby: z.any().optional(),
    createdby: z.any().optional(),
    assignedto: z.any().optional(),
    usageProperty: z.string().optional(),
    referrer: z.string().optional(),
    contactFrom: z.string(),
    requirementStatus: z.string().optional(),
    phone: z.string(),
    propertyOfInterest: z.string().optional(),
    propertyLocation: z.string().optional(),
    typeOfCapture: z.string().optional(),
    aspiredPrice: z.string().optional(),
    typeOfBusiness: z.string().optional(),
    note: z.string().optional(),
    isPotentialInvestor: z.boolean().optional(),
    amountOfPeople: z.number().int().optional(),
    amountOfPets: z.number().int().optional(),
    amountOfYounger: z.number().int().optional(),
    arrivingDate: z.string().optional().nullable(),
    checkoutDate: z.string().optional().nullable(),
    amountOfNights: z.number().int().optional(),
    reasonOfStay: z.string().optional(),
    usageOfProperty: z.string().optional(),
    typeOfPerson: z.string().optional(),
    personEntry: z.string().optional(),
    personHeadquarters: z.string().optional(),
    personLocation: z.string().optional(),
    specificRequirement: z.string().optional(),
    location: z.string().optional(),
    company: z.string().optional(),
    remodeledAreas: z.string().optional(),
    propertyDistribution: z.string().optional().nullable(),
    m2: z.string().optional(),
    occupation: z.string().optional(),
    userFullName: z.string().optional().nullable(),
    userId: z.string().optional().nullable(),
    serviceName: z.string().optional().nullable(),
    serviceId: z.string().optional().nullable(),
    subServiceName: z.string().optional().nullable(),
    subServiceId: z.string().optional().nullable(),
    username: z.string().optional().nullable(),
    interestDate: z.string().optional().nullable(),
    appointmentDate: z.string().optional().nullable(),
    inspectionDate: z.string().optional().nullable(),
    zonesOfInterest: z.array(z.string()).optional(),
    essentialFeatures: z.array(z.string()).optional(),
    propertytype: z.string().max(256),
    allowpets: z.string().max(256),
    allowyounger: z.string().max(256),
    requestracking: z.string().optional(),
    isinwaitinglist: z.boolean().optional(),
    budgetfrom: z.any().optional(),
    budgetto: z.any().optional(),
    status: z.string().max(255),
    adviserId: z.string().max(255),
    adviserName: z.string().max(255),
});

export type ClientDtoType = z.infer<typeof ClientDto>;
